spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:/config/app.yml
      - classpath:/config/database.yml
      - classpath:/config/web.yml

logging:
  level:
    org.springdoc: ERROR